package io.lifeengine.cryptobot.observability;

import io.lifeengine.cryptobot.CryptobotServiceApplication;
import io.lifeengine.cryptobot.testsupport.StubRepositoriesConfiguration;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.reactive.server.WebTestClient;

/**
 * End-to-end contract for the build identity on {@code /actuator/info} (T7, mirroring Auth
 * LIFE-OPS-02 §2.2). Boots the full app with security ENABLED (the {@code test} profile sets
 * {@code cryptobot.security.enabled=true}), so it also proves that {@code /actuator/info} is
 * internal-readable without a token while {@code /api/cryptobot/**} still requires auth. The git block is
 * populated from the real {@code git.properties} generated by git-commit-id during this build.
 *
 * <p>Repositories come from {@link StubRepositoriesConfiguration}; the test profile excludes R2DBC + Flyway
 * autoconfig. The test never touches a repository — {@code /api/cryptobot/**} is rejected by the JWT filter
 * before routing.
 */
@SpringBootTest(
        classes = {CryptobotServiceApplication.class, StubRepositoriesConfiguration.class},
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureWebTestClient
@ActiveProfiles("test")
@TestPropertySource(
        properties = {
            // Proves deployment.environment is configuration-driven, not hardcoded.
            "lifeengine.deployment.env=citest",
            "management.endpoints.web.exposure.include=health,info,prometheus"
        })
class CryptobotActuatorInfoIdentityTest {

    @Autowired
    private WebTestClient webTestClient;

    @Test
    @DisplayName("GET /actuator/info (no auth) → 200 with §2.2 identity: real commit, env from config")
    void actuatorInfoExposesBuildIdentity() {
        webTestClient
                .get()
                .uri("/actuator/info")
                .exchange()
                .expectStatus()
                .isOk()
                .expectBody()
                .jsonPath("$.service.name")
                .isEqualTo("cryptobot-service")
                .jsonPath("$.service.version")
                .isNotEmpty()
                // From lifeengine.deployment.env — configuration-driven.
                .jsonPath("$.deployment.environment")
                .isEqualTo("citest")
                // Real commit from git.properties generated by git-commit-id in this build.
                .jsonPath("$.git.commit.id")
                .isNotEmpty()
                .jsonPath("$.build.timestamp")
                .isNotEmpty();
    }

    @Test
    @DisplayName("/actuator/info is internal-readable, but a protected route still denies (no over-exposure)")
    void actuatorInfoDoesNotLoosenSecurity() {
        webTestClient.get().uri("/actuator/info").exchange().expectStatus().isOk();
        webTestClient.get().uri("/api/cryptobot/snapshots/BTCUSDT").exchange().expectStatus().isUnauthorized();
    }
}
